version: '3'
services:
  mongo:
    image: mongo:3.4-jessie
    volumes:
      - ./mongo/mongo-data/:/data/db/
      - ./mongo/mongo-backup/:/mongo-backup/
    ports:
      - 27017:27017
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 3050:80
  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend/node_modules/:/app/node_modules
      - ./backend:/app
  client:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend/node_modules/:/app/node_modules
      - ./frontend:/app